Repository modx-pro/miniShop2, pull requests merged in 2020-12, with the labels that each got.

#486 Исправлена проблема с "Cannot read property items of undefined" и поправил порядок вкладок при создании товара
  assets/components/minishop2/js/mgr/category/update.js
  assets/components/minishop2/js/mgr/product/create.js
  assets/components/minishop2/js/mgr/product/update.js
Labels: pr-state/review-needed

#417 Изменение любых полей продукта по событию msOnGetProductFields
  _build/data/transport.events.php
  core/components/minishop2/elements/snippets/snippet.ms_products.php
  core/components/minishop2/model/minishop2/msproduct.class.php
  core/components/minishop2/model/minishop2/msproductdata.class.php
Labels: pr-state/review-needed

#490 Добавлена сумма для бесплатной доставки
  _build/resolvers/resolve.tables.php
  assets/components/minishop2/js/mgr/settings/delivery/grid.js
  assets/components/minishop2/js/mgr/settings/delivery/window.js
  core/components/minishop2/lexicon/be/manager.inc.php
  core/components/minishop2/lexicon/de/manager.inc.php
  core/components/minishop2/lexicon/en/manager.inc.php
  core/components/minishop2/lexicon/fr/manager.inc.php
  core/components/minishop2/lexicon/it/manager.inc.php
  core/components/minishop2/lexicon/lt/manager.inc.php
  core/components/minishop2/lexicon/nl/manager.inc.php
  core/components/minishop2/lexicon/ro/manager.inc.php
  core/components/minishop2/lexicon/ru/manager.inc.php
  core/components/minishop2/lexicon/uk/manager.inc.php
  core/components/minishop2/model/minishop2/msdeliveryhandler.class.php
  core/components/minishop2/model/minishop2/mysql/msdelivery.map.inc.php
  core/components/minishop2/model/schema/minishop2.mysql.schema.xml
Labels: enhancement, pr-state/review-needed

#491 add order product's options interface
  _build/data/transport.settings.php
  assets/components/minishop2/js/mgr/orders/orders.window.product.js
  core/components/minishop2/controllers/mgr/orders.class.php
  core/components/minishop2/lexicon/ru/setting.inc.php
  core/components/minishop2/processors/mgr/orders/product/get.class.php
  core/components/minishop2/processors/mgr/orders/product/update.class.php
Labels: enhancement, pr-state/review-needed

#497 В классе корзины в метод status добавлен подсчет скидки
  assets/components/minishop2/js/web/default.js
  core/components/minishop2/elements/snippets/snippet.ms_cart.php
  core/components/minishop2/model/minishop2/mscarthandler.class.php
Labels: enhancement

#504 Update fun pathinfo
  core/components/minishop2/model/minishop2/minishop2.class.php
Labels: pr-state/review-needed

#503 Update default.js
  assets/components/minishop2/js/web/default.js
Labels: pr-state/review-needed

#513 Set checkbox value
  core/components/minishop2/processors/mgr/settings/option/types/checkbox.class.php
Labels: pr-state/review-needed

#509 Показываем все категории
  core/components/minishop2/processors/mgr/category/getnodes.class.php
Labels: pr-state/review-needed

#508 Модификатор вместо функции
  core/components/minishop2/elements/chunks/chunk.ms_cart.tpl
Labels: pr-state/review-needed
