Repository modx-pro/miniShop2, pull requests merged in 2020-06, with the labels that each got.

#421 Add msorder_remove permission
  _build/data/transport.policies.php
  _build/data/transport.policytemplates.php
  core/components/minishop2/lexicon/en/permissions.inc.php
  core/components/minishop2/lexicon/ro/permissions.inc.php
  core/components/minishop2/lexicon/ru/permissions.inc.php
  core/components/minishop2/processors/mgr/orders/remove.class.php
Labels: pr-state/ready-for-merging

#407 Added sorting sortOptions in msOptions, msProductOptions
  _build/properties/properties.ms_options.php
  _build/properties/properties.ms_product_options.php
  core/components/minishop2/elements/snippets/snippet.ms_options.php
  core/components/minishop2/elements/snippets/snippet.ms_product_options.php
  core/components/minishop2/lexicon/en/properties.inc.php
  core/components/minishop2/lexicon/ru/properties.inc.php
Labels: enhancement, pr-state/review-needed

#432 Added renderBadge to statuses
  assets/components/minishop2/css/mgr/main.css
  assets/components/minishop2/js/mgr/misc/ms2.utils.js
  assets/components/minishop2/js/mgr/orders/orders.grid.js
  assets/components/minishop2/js/mgr/settings/status/grid.js
  core/components/minishop2/controllers/mgr/orders.class.php
  core/components/minishop2/processors/mgr/orders/getlist.class.php
Labels: enhancement, pr-state/review-needed

#430 Добавил ссылку на системные настройки в меню miniShop2
  _build/data/transport.menu.php
  core/components/minishop2/lexicon/en/default.inc.php
  core/components/minishop2/lexicon/ru/default.inc.php
Labels: enhancement, pr-state/review-needed

#433 Refactoring `sortOptionValues` property
  _build/properties/properties.ms_options.php
  _build/properties/properties.ms_product_options.php
  core/components/minishop2/elements/snippets/snippet.ms_options.php
  core/components/minishop2/elements/snippets/snippet.ms_product_options.php
  core/components/minishop2/lexicon/en/properties.inc.php
  core/components/minishop2/lexicon/ru/properties.inc.php
  core/components/minishop2/model/minishop2/minishop2.class.php
Labels: pr-state/review-needed

#435 Added buttons on orders and settings pages
  assets/components/minishop2/js/mgr/orders/orders.js
  assets/components/minishop2/js/mgr/settings/settings.js
  assets/components/minishop2/js/mgr/settings/settings.panel.js
  core/components/minishop2/controllers/mgr/orders.class.php
  core/components/minishop2/controllers/mgr/settings.class.php
Labels: enhancement, pr-state/review-needed

#438 Исправление бага с созданием источника файлов при обновлении, если он был переименован
  _build/resolvers/resolve.sources.php
Labels: pr-state/review-needed

#393 Нумерация заказа MS2
  _build/data/transport.settings.php
  core/components/minishop2/lexicon/ru/setting.inc.php
  core/components/minishop2/model/minishop2/msorderhandler.class.php
Labels: enhancement, pr-state/review-needed

#436 Возможность обновления нескольких мини-корзин на странице.
  assets/components/minishop2/css/web/default.css
  assets/components/minishop2/js/web/default.js
  core/components/minishop2/elements/chunks/chunk.ms_minicart.tpl
Labels: enhancement, pr-state/awaiting-an-author
