Repository modx-pro/miniShop2, pull requests merged in 2020-11, with the labels that each got.

#467 Fix bug `property 'id' of undefined` #466
  assets/components/minishop2/js/mgr/category/category.common.js
Labels: pr-state/review-needed

#470 Added ms2_frontend_country lexicon
  core/components/minishop2/lexicon/be/default.inc.php
  core/components/minishop2/lexicon/de/default.inc.php
  core/components/minishop2/lexicon/en/default.inc.php
  core/components/minishop2/lexicon/fr/default.inc.php
  core/components/minishop2/lexicon/gr/default.inc.php
  core/components/minishop2/lexicon/it/default.inc.php
  core/components/minishop2/lexicon/lt/default.inc.php
  core/components/minishop2/lexicon/nl/default.inc.php
  core/components/minishop2/lexicon/ro/default.inc.php
  core/components/minishop2/lexicon/ru/default.inc.php
  core/components/minishop2/lexicon/uk/default.inc.php
Labels: enhancement

#469 Added displaying of the alt attribute and title in the gallery chunk
  core/components/minishop2/elements/chunks/chunk.ms_gallery.tpl
Labels: enhancement, pr-state/review-needed

#468 Fixed sorting by customer field in the order list
  core/components/minishop2/processors/mgr/orders/getlist.class.php
Labels: pr-state/review-needed

#471 Added micro-markup
  core/components/minishop2/elements/chunks/chunk.ms_product_content.tpl
  core/components/minishop2/elements/chunks/chunk.ms_products_row.tpl
Labels: enhancement, pr-state/review-needed

#472 Fix alt and titile msGallery
  assets/components/minishop2/js/web/lib/fotorama.min.js
Labels: pr-state/review-needed

#480 Fix visual bug
  assets/components/minishop2/css/mgr/main.css
Labels: pr-state/review-needed

#484 Added `return` property to `msProductOptions` snippet
  core/components/minishop2/elements/snippets/snippet.ms_product_options.php
Labels: pr-state/review-needed

#483 Added `ignoreGroups` and `sortGroups` to `msProductOptions` snippet
  _build/properties/properties.ms_product_options.php
  core/components/minishop2/elements/snippets/snippet.ms_product_options.php
  core/components/minishop2/lexicon/en/properties.inc.php
  core/components/minishop2/lexicon/ru/properties.inc.php
Labels: enhancement, pr-state/review-needed

#478 Added an example of displaying product content on Fenom
  _build/data/transport.chunks.php
  core/components/minishop2/elements/chunks/chunk.ms_product_content_fenom.tpl
Labels: pr-state/review-needed

#489 Исправление baseUrl в медиаисточнике
  _build/resolvers/resolve.sources.php
Labels: pr-state/review-needed

#482 Fix PHP warning: count()
  core/components/minishop2/processors/mgr/product/getlist.class.php
Labels: pr-state/review-needed
