Repository modx-pro/miniShop2, pull requests merged in 2020-09, with the labels that each got.

#460 Задал кодировку для корректного отображения сообщений сборщика
  _build/build.transport.php
Labels: pr-state/review-needed

#455 Вывод вкладки галереи при создании товара
  assets/components/minishop2/js/mgr/product/create.js
  core/components/minishop2/controllers/product/create.class.php
  core/components/minishop2/lexicon/en/product.inc.php
Labels: enhancement

#459 Изменил порядок вкладок для категории
  assets/components/minishop2/js/mgr/category/category.common.js
  assets/components/minishop2/js/mgr/category/update.js
Labels: enhancement, pr-state/review-needed

#461 Updated snippets: msCart, msOrder, msGetOrder and msGallery
  core/components/minishop2/elements/snippets/snippet.ms_cart.php
  core/components/minishop2/elements/snippets/snippet.ms_gallery.php
  core/components/minishop2/elements/snippets/snippet.ms_get_order.php
  core/components/minishop2/elements/snippets/snippet.ms_order.php
Labels: enhancement, pr-state/review-needed
