Repository modx-pro/miniShop2, pull requests merged in 2021-03, with the labels that each got.

#539 refactoring filter_options
  core/components/minishop2/elements/snippets/snippet.ms_products.php
Labels: pr-state/review-needed

#542 Концепция рефакторинга подключения скриптов уведомлений
  _build/data/transport.settings.php
  assets/components/minishop2/js/web/default.js
  assets/components/minishop2/js/web/message_settings.js
  core/components/minishop2/model/minishop2/minishop2.class.php
Labels: enhancement

#555 Fix for "bad fix" of Recoverable error
  core/components/minishop2/model/minishop2/msproductdata.class.php
Labels: pr-state/review-needed

#547 Отображение значения опции товара на странице категории товаров #535
  .gitignore
  core/components/minishop2/processors/mgr/product/getlist.class.php
Labels: pr-state/review-needed

#553 Добавлена поддержка параметра return в msProducts
  _build/properties/properties.ms_products.php
  core/components/minishop2/elements/snippets/snippet.ms_products.php
  core/components/minishop2/lexicon/en/properties.inc.php
  core/components/minishop2/lexicon/ru/properties.inc.php
Labels: enhancement, pr-state/review-needed
